#ifndef SG_MCU_CON_CONTROL_TYPE_ENUM_H
#define SG_MCU_CON_CONTROL_TYPE_ENUM_H

enum CONTINUOUS_CONTROL_TYPE_ENUM {
  CON_CTRL_UNKNOWN = -1,
  CON_CTRL_NONE = 0,
  CON_CTRL_TIMER = 1,
  CON_CTRL_CRITERIA = 2,
  CON_CTRL_RANGE = 3,
};

#endif //SG_MCU_CON_CONTROL_TYPE_ENUM_H
