# We can change sg mode by replace following mode to 'v2'
# v1 = SG 2019
# v2 = SG LTS
# v2_simplex = SG LTS + LORA MODE
# v2_solution = SG LTS + GSOLUTION

# ONLY developer

[platformio]
default_envs = v2_dev

[env]

[env:v1]
platform = espressif32@3.5.0
board = node32s
framework = arduino
monitor_speed = 345600
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps =
  TaskScheduler@3
  ArduinoJson@6.21.5
  RTClib@2.1.1
  6497
lib_ignore =
	TinyWireM
lib_ldf_mode = deep+
build_flags =
	-DSG_VERSION_V1

[env:v1_simplex]
platform = espressif32@3.5.0
board = node32s
framework = arduino
monitor_speed = 345600
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps =
  TaskScheduler@3
  ArduinoJson@6.21.5
  RTClib@2.1.1
  6497
lib_ignore =
	TinyWireM
lib_ldf_mode = deep+
build_flags =
	-DSG_VERSION_V1
	-DSG_COMMUNICATION_SIMPLEX

[env:v1_dev]
platform = espressif32@3.5.0
board = node32s
framework = arduino
monitor_speed = 345600
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps =
  TaskScheduler@3
  ArduinoJson@6.21.5
  RTClib@2.1.1
  6497
lib_ignore =
	TinyWireM
lib_ldf_mode = deep+
build_flags =
	-DSG_VERSION_V1
	-DSG_MODE_DEVELOPMENT

[env:v2]
platform = espressif32@3.5.0
board = node32s
framework = arduino
monitor_speed = 345600
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps =
  TaskScheduler@3
  ArduinoJson@6.21.5
  RTClib@2.1.1
  6497
lib_ignore =
	TinyWireM
lib_ldf_mode = deep+
build_flags =
	-DSG_VERSION_V2

[env:v2_simplex]
platform = espressif32@3.5.0
board = node32s
framework = arduino
monitor_speed = 345600
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps =
  TaskScheduler@3
  ArduinoJson@6.21.5
  RTClib@2.1.1
  6497
lib_ignore =
	TinyWireM
lib_ldf_mode = deep+
build_flags =
	-DSG_VERSION_V2
	-DSG_COMMUNICATION_SIMPLEX

[env:v2_dev]
platform = espressif32@3.5.0
board = node32s
framework = arduino
monitor_speed = 345600
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps =
  TaskScheduler@3
  ArduinoJson@6.21.5
  RTClib@2.1.1
  6497
lib_ignore =
	TinyWireM
lib_ldf_mode = deep+
upload_speed = 921600
build_flags =
	-DSG_VERSION_V2
	-DSG_MODE_DEVELOPMENT

[env:v2_uno]
platform = espressif32@3.5.0
board = node32s
framework = arduino
monitor_speed = 345600
build_type = debug
monitor_filters = esp32_exception_decoder
lib_deps =
  TaskScheduler@3
  ArduinoJson@6.21.5
  RTClib@2.1.1
  6497
lib_ignore =
	TinyWireM
lib_ldf_mode = deep+
build_flags =
	-DSG_VERSION_V2
upload_speed = 115200

[env:native_protocol]
platform = native
test_framework = unity
test_build_src = no
build_flags =
	-Isrc
	-std=gnu++17
