#ifndef SG_MCU_SEQ_CONTROL_TYPE_ENUM_H
#define SG_MCU_SEQ_CONTROL_TYPE_ENUM_H

enum SEQUENCE_CONTROL_TYPE_ENUM {
  SEQ_CTRL_UNKNOWN = -1,
  SEQ_CTRL_NONE = 0,
  SEQ_CTRL_TIMER = 1,
  SEQ_CTRL_CRITERIA = 2,
  SEQ_CTRL_RANGE = 3,
};

#endif //SG_MCU_SEQ_CONTROL_TYPE_ENUM_H
