#ifndef SG_MCU_PRECONDITION_TYPE_ENUM_H
#define SG_MCU_PRECONDITION_TYPE_ENUM_H

enum PRECONDITION_TYPE_ENUM {
  PREC_UNKNOWN = -1,
  PREC_NONE = 0,
  PREC_TIMER = 1,
  PREC_CRITERIA = 2,
  PREC_RANGE = 3
};

#endif //SG_MCU_PRECONDITION_TYPE_ENUM_H
