#ifndef SG_MCU_CONTROL_TYPE_ENUM_H
#define SG_MCU_CONTROL_TYPE_ENUM_H

enum CONTROL_TYPE_ENUM {
  CH_CTRL_UNKNOWN = -1,
  CH_CTRL_NONE = 0,
  CH_CTRL_MANUAL = 1,
  CH_CTRL_TIMER = 2,
  CH_CTRL_CRITERIA = 3,
  CH_CTRL_RANGE = 4,
  CH_CTRL_PAR = 5
};

#endif //SG_MCU_CONTROLTYPEENUM_H
