#ifndef SG_MCU_CONTROL_TYPE_ENUM_H
#define SG_MCU_CONTROL_TYPE_ENUM_H

enum CONTROL_TYPE_ENUM {
  CTRL_UNKNOWN = -1,
  CTRL_NONE = 0,
  CTRL_MANUAL = 1,
  CTRL_TIMER = 2,
  CTRL_CRITERIA = 3,
  CTRL_RANGE = 4,
};

#endif //SG_MCU_CONTROLTYPEENUM_H
